### ISSUE TITLE
CameraV1GLSurfaceView 这个看不到东西啊，

### ISSUE THREAD

**Issue by shanyaodan** [lb377463323/GraphicsTestBed#1]
我的手机是小米6，CameraV2能看到东西，CameraV1看不到东西

**Comment by lb377463323** [comment]
有没有提示上面错误？代码是很早之前写的，可能不太完善，你可以先试下删除CameraV1 -> openCamera() -> parameters.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);

**Comment by shanyaodan** [comment]
已经解决了 mGLSurfaceView.init(mCamera, false);设置成true就行了

**Comment by lb377463323** [comment]
true是说明已经开启预览了，这样改不太合理啊

**Comment by lb377463323** [comment]
你黑屏有没有提示什么BUG，我这边没有小米6，没法测试，但是直接改成true就启动不了预览了啊
