### ISSUE TITLE
请教个激活纹理的问题

### ISSUE THREAD

**Issue by jtyang** [lb377463323/GraphicsTestBed#3]
请问下为何使用GLSurfaceView的时候，onDrawFrame()开始激活纹理使用的是glActiveTexture(GLES20.GL_TEXTURE0);而使用TextureView的时候，drawTexture()开始的激活纹理却是glActiveTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES)呢？

谢谢！

**Comment by lb377463323** [comment]
@jtyang 抱歉，这是我的错，不论是激活2D、3D还是OES纹理，都应该这样：glActiveTexture(GL_TEXTURE0 + n); //n为0,1,2......，代码已改正。
