### ISSUE TITLE
onCaptureProgressed, 不需要进行什么操作吗？

### ISSUE THREAD

**Issue by David-Lee-1990** [lb377463323/GraphicsTestBed#7]
`    private CameraCaptureSession.CaptureCallback mCaptureCallback = new CameraCaptureSession.CaptureCallback() {
        @Override
        public void onCaptureProgressed(CameraCaptureSession session, CaptureRequest request, CaptureResult partialResult) {
        }`

请问，onCaptureProgressed, 不需要进行什么操作吗？  takePicture函数在哪里调用了？

**Comment by lb377463323** [comment]
这是camera API 2，没有takePicture了
